# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c344eb2bdfc007627d8c177175c70a847e7f5cd8ce017200c09bd4a0d38161cd24b147a0137f175c924a3476e6e29d19ba79a00eecb0b443a4b447384432f67

test:
  secret_key_base: b90b96d955cb420109fbd74aa373914cf5353fcc1a5dcc973b15779143eaf5892fe0a9f7d4826c2ab68e91bb59b36fc300e9ace553f1c9ca5512f179c062beb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
